# Generated by Django 3.2.5 on 2021-07-21 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometryShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(help_text='Unique name for geometric shape', max_length=255)),
            ],
            options={
                'db_table': 'geometry_shapes',
            },
        ),
        migrations.CreateModel(
            name='OwnMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(help_text='Timestamp when own mood created')),
                ('geometry_shape', models.ForeignKey(db_column='geometry_shape_id', on_delete=django.db.models.deletion.CASCADE, to='moods.geometryshape')),
            ],
            options={
                'db_table': 'own_moods',
            },
        ),
        migrations.CreateModel(
            name='SharedMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(help_text='Timestamp when shared mood created')),
                ('geometry_shape', models.ForeignKey(db_column='geometry_shape_id', on_delete=django.db.models.deletion.CASCADE, to='moods.geometryshape')),
            ],
            options={
                'db_table': 'shared_moods',
            },
        ),
        migrations.CreateModel(
            name='TokenOwnMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_mood', models.ForeignKey(db_column='own_mood_id', on_delete=django.db.models.deletion.CASCADE, to='moods.ownmood')),
                ('token', models.ForeignKey(db_column='token_id', on_delete=django.db.models.deletion.CASCADE, to='tokens.token')),
            ],
            options={
                'db_table': 'token_own_moods',
            },
        ),
        migrations.CreateModel(
            name='SharedMoodGeometryShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_in_list', models.IntegerField(help_text='Used for restore sparse list')),
                ('color', models.IntegerField(help_text='Color in flutter 0xFF000000')),
                ('geometry_shape', models.ForeignKey(db_column='geometry_shape_id', on_delete=django.db.models.deletion.CASCADE, to='moods.geometryshape')),
                ('shared_mood', models.ForeignKey(db_column='shared_mood_id', on_delete=django.db.models.deletion.CASCADE, to='moods.sharedmood')),
            ],
            options={
                'db_table': 'shared_mood_geometry_shapes',
            },
        ),
        migrations.CreateModel(
            name='OwnMoodGeometryShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_in_list', models.IntegerField(help_text='Used for restore sparse list')),
                ('color', models.IntegerField(help_text='Color in flutter 0xFF000000')),
                ('geometry_shape', models.ForeignKey(db_column='geometry_shape_id', on_delete=django.db.models.deletion.CASCADE, to='moods.geometryshape')),
                ('own_mood', models.ForeignKey(db_column='own_mood_id', on_delete=django.db.models.deletion.CASCADE, to='moods.ownmood')),
            ],
            options={
                'db_table': 'own_mood_geometry_shapes',
            },
        ),
        migrations.AddConstraint(
            model_name='geometryshape',
            constraint=models.UniqueConstraint(fields=('mnemonic',), name='unique shame name'),
        ),
        migrations.AlterUniqueTogether(
            name='tokenownmood',
            unique_together={('token', 'own_mood')},
        ),
        migrations.AlterUniqueTogether(
            name='sharedmoodgeometryshape',
            unique_together={('shared_mood', 'index_in_list', 'geometry_shape')},
        ),
        migrations.AlterUniqueTogether(
            name='ownmoodgeometryshape',
            unique_together={('own_mood', 'index_in_list', 'geometry_shape')},
        ),
    ]
