# syntax=docker/dockerfile:1
FROM nginx:alpine

RUN apk add --no-cache openjdk8
RUN apk add --no-cache sqlite

COPY ./target/web/ /usr/share/nginx/html/
COPY ./nginx.212 /etc/nginx/conf.d/default.conf

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
EXPOSE 80
CMD nginx && java -jar /app.jar
