# syntax=docker/dockerfile:1
FROM nginx:alpine

RUN apk add --no-cache python3
RUN apk add --no-cache py3-pip
RUN apk add --no-cache sqlite

COPY .pub-build/web/ /usr/share/nginx/html/
COPY ./nginx.213 /etc/nginx/conf.d/default.conf

COPY . .
RUN pip install -r requirements.txt
RUN export DJANGO_SECRET_KEY=`python3 -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'` && export DJANGO_DEBUG=False && python3 manage.py migrate
RUN export DJANGO_SECRET_KEY=`python3 -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'` && export DJANGO_DEBUG=False && python3 manage.py loaddata app_moods/fixtures/geometry_shapes.yaml
EXPOSE 80
ENV PYTHONUNBUFFERED=1
CMD nginx && export DJANGO_SECRET_KEY=`python3 -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'` && export DJANGO_DEBUG=False && python3 manage.py runserver 127.0.0.1:8000
